services:
  dev-env:
    build:
      context: .
      dockerfile: Dockerfile
    image: commitment-img
    container_name: 3170-env
    ports:
      - "3001:3000"
    volumes:
      - ./commitment:/projects/commitment/server
    env_file:
      - ./commitment/server/.env
    tty: true
    stdin_open: true

  server:
    image: server:1.0.0
    container_name: ${SERVER_HOST}
    build:
      context: ./commitment/server
      dockerfile: ./Dockerfile
    env_file:
      - ./commitment/server/.env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./commitment/server:/server
      - server-v-node-modules:/server/node_modules

  database:
    image: database:1.0.0
    container_name: ${DATABASE_HOST}
    build:
      context: ./commitment/database
      dockerfile: ./Dockerfile
    env_file:
      - ./commitment/server/.env
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - database-v:/data/db

volumes:
  server-v-node-modules: {}
  database-v: {}
