services:
  dev-env:
    build:
      context: .
      dockerfile: Dockerfile
    image: commitment-img
    container_name: 3170-env
    ports:
      - "3001:3000"
    volumes:
      - ./commitment:/projects/commitment
    env_file:
      - ./commitment/server/.env
    tty: true
    stdin_open: true

  server:
    image: server:1.0.0
    container_name: server
    build:
      context: ./commitment/server
      dockerfile: ./Dockerfile
    env_file:
      - ./commitment/server/.env
    ports:
      - "3000:3000"
    volumes:
      - ./commitment/server:/server
       - server-v-node-modules:/server/node_modules
    tty: true
    stdin_open: true

  database:
    image: database:1.0.0
    container_name: mongodb
    build:
      context: ./commitment/database
      dockerfile: ./Dockerfile
    env_file:
      - ./commitment/server/.env
    ports:
      - "27017:27017"
    volumes:
      - database-v:/data/db
    tty: true
    stdin_open: true

volumes:
  server-v-node-modules: {}
  database-v: {}
