services:
  dev-env:
    build: .
    image: commitment-img
    container_name: 3170-env
    ports:
      - "3000:3000"
    volumes:
      - ./commitment:/projects/commitment
    env_file:
      - .env
    environment:
      - MONGO_URL=${MONGO_URL}
    depends_on:
      - mongo
    tty: true
    stdin_open: true

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

volumes:
  mongo-data: