services:
  build-env:
    build:
      context: ./commitment
      dockerfile: Dockerfile.MeteorDev
    image: commitment-img
    container_name: 3170-build
    ports:
      - "3000:3000"
    volumes:
      - ./commitment:/projects/commitment
    env_file:
      - ./commitment/.env
    tty: true
    stdin_open: true
    networks:
      - app-network

  haskell-api:
    build:
      context: ./api
      dockerfile: Dockerfile.haskell
    image: haskell-api-img
    container_name: haskell-api
    volumes:
      - ./commitment:/projects/api
    ports:
      - "8081:8081"
    networks:
      - app-network

  python-executor:
    build:
      context: ./python_executor
      dockerfile: Dockerfile
    volumes:
      - ./python_executor:/projects/python_executor
    image: python-executor-img
    container_name: python-executor
    security_opt:
      - seccomp:./python_executor/seccomp-bwrap.json
    tty: true
    stdin_open: true
    ports:
      - "8002:8002"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
