require('dotenv').config();

const DATABASE_USERNAME = process.env.MONGO_INITDB_ROOT_USERNAME;
const DATABASE_PASSWORD = process.env.MONGO_INITDB_ROOT_PASSWORD;
const DATABASE_DB = process.env.MONGO_INITDB_ROOT_DATABASE;
const DATABASE_HOST = process.env.MONGO_INITDB_ROOT_HOST;
const DATABASE_PORT = process.env.MONGO_INITDB_ROOT_PORT;
const DATABASE_COLLECTION = process.env.MONGO_INITDB_ROOT_COLLECTION;

const SERVER_HOST = process.env.SERVER_HOST;
const SERVER_PORT = process.env.SERVER_PORT;

const ATLAS_MONGODB_URI = process.env.ATLAS_MONGODB_URI

console.log('loading this')
console.log(`${process.env.DATABASE_USERNAME}`)

module.exports = {
    DATABASE_USERNAME,
    DATABASE_PASSWORD,
    DATABASE_DB,
    DATABASE_HOST,
    DATABASE_PORT,
    DATABASE_COLLECTION,
    SERVER_HOST,
    SERVER_PORT,
    ATLAS_MONGODB_URI
}