name: Deploy to EC2

on:
  push:
    branches:
      - "cd/deploy"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (for logs only, optional)
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Run deploy script on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'bash -s' << 'EOF'
            cd /home/ubuntu/app || exit 1
            chmod +x deploy.sh
            ./deploy.sh
          EOF
