name: Commitment Checks

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  tasks:
    name: Run ${{ matrix.task }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./commitment

    strategy:
      matrix:
        task: [lint, typecheck, test]

    services:
      mongo:
        image: mongo:5.0
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Meteor
        run: curl https://install.meteor.com/ | sh

      - name: Install npm dependencies
        run: meteor npm install
      
      - name: Run task
        run: |
          if [ "${{ matrix.task }}" = "lint" ]; then
            npx eslint client server tests --quiet
          elif [ "${{ matrix.task }}" = "typecheck" ]; then
            meteor npm run typecheck
          elif [ "${{ matrix.task }}" = "test" ]; then
            meteor npm run test
          fi
