name: Meteor Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: --bind_ip_all

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Meteor
        run: curl https://install.meteor.com/ | sh

      - name: Install npm dependencies
        run: meteor npm install

      - name: Run Mocha tests
        run: meteor npm run test
